version: '3.1'
services:
  postgres:
    image: postgres
    container_name: "PostgreSQL_Test"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - test_data:/var/lib/mysql

volumes:
  test_data: